language/exceptions.xml
I noticed some errors in that documentation while reading it, quite usual French errors.
Now fixed 😉
=> Fixing errors in Exceptions documentation

README.md
http://pear.php.net/manual/fr/standards.php doesn't exist and returns a 404 error: there's no french version of this page. So I replaced it with the english URL: http://pear.php.net/manual/en/standards.php
=> Wrong URL for Pear Coding Standards

reference/datetime/datetimeinterface/diff.xml
Hi 🖖
Fix typo in doc for datetime
=> docs(datetime): fix typo

README.md
During the process of translating the README.md file for the doc-it repository, I found some old things and I fixed them. I'm sure you can also edit some old references to some steps that are no more required now.
=> Add references to doc.php.net and use github.com instead of git.php.net

reference/strings/functions/addslashes.xml
The reference page for the `addslashes` function contains several typos.
=> Fix typos in addslashes reference page

reference/var/functions/is-callable.xml
Based on this diff :http://doc.php.net/revcheck.php?p=plain&lang=fr&hbp=4807f1a19e7fafc1d9fa0ac49a2beb368c6206fa&f=reference/var/functions/is-callable.xml&c=on
This only changes `function` tag to `link`. The text remains the same.
=> Update reference/var/functions/is-callable to English revision

language/functions.xml
This makes it clearer for the user.
=> Use "exécution immédiate" instead of "exécution avide"

reference/array/functions/array-search.xml
The description was ambiguous, `array_search` return the first key corresponding to the passed value, not the key corresponding to the first value.
=> Make French translation clearer for array_search

reference/outcontrol/functions/ob-start.xml
The word "contenu" was mis-spelled "contenue" in L49.
=> Typo fix in ob-start.xml

language/types/array.xml
Two typos from manual page: https://www.php.net/manual/fr/language.types.array.php:
> La raison est que ce code a une constante indéfinie (bar) plutôt qu'une chaîne de caractères ('bar' - noter les guillemets).
Should be:
La raison est que ce code a une constante indéfinie (bar) plutôt qu'une chaîne de caractères ('bar' - notez les guillemets).
And
> Voir les exemples ci-dessous pour plus détails mais aussi la section sur l'analyse des variables dans les chaînes.
Should be:
Voir les exemples ci-dessus pour plus de détails mais aussi la section sur l'analyse des variables dans les chaînes.
=> Types Array: fix 2 grammatical typos

reference/pcre/functions/preg-match.xml
Duplicate "survient" in the return value of the preg_match function documentation
=> FIX: Typo in preg_match.xml

reference/array/functions/array-diff.xml
Replaced a reference to **array1** by correct reference to **array** in description.
Fixes https://github.com/php/doc-fr/issues/148
=> Fix a typo in description of array_diff

reference/mail/functions/mail.xml
=> Corrected PHP mail() function arguments names in French documentation

language/control-structures/goto.xml
Bonjour :wave: :slightly_smiling_face: ,
The description of the `goto` is wrong, mainly because a part of the original english text is missing.
https://github.com/php/doc-en/blob/2ef411d8ef4f8e3ecbcb9c23fbb8017061e44501/language/control-structures/goto.xml#L21-L26
```
The target
label must be within the same file and context, meaning that you cannot jump
out of a function or method, nor can you jump into one.  You also
cannot jump into any sort of loop or switch structure.  You may jump
out of these, and a common use is to use a <literal>goto</literal>
in place of a multi-level <literal>break</literal>.
```
Previous version was suggesting that it's possible to jump out of a function with a `goto`.
I did my best to propose something else :sweat_smile: 
Thanks for your amazing work on this …
=> Fixi goto description

reference/session/security.xml
I might have found what seems to be typos in French php-doc of session security.xml file. 
Trying to help the php community as much as I can.
Have a great day php core team and all of you awesome php contributors.
=> Fix typos in French translation of security.xml

reference/mysqli/mysqli_result/fetch-fields.xml
This PR closes the bug report ([80797](https://bugs.php.net/bug.php?id=80797)) and fixes the issues of the `mysqli_fetch_fields` signature being out-of-order since the a9a52c5 commit.
This is my first PR to a translation so not 100% if this is the right way to go about it, but with this PR the document should be up-to-date with the current revision.
=> [80797] Fix mysqli_fetch_fields is missing the "s"

reference/apcu/apcuiterator.xml, reference/apcu/apcuiterator/construct.xml, reference/apcu/apcuiterator/current.xml, reference/apcu/apcuiterator/gettotalcount.xml, reference/apcu/apcuiterator/gettotalhits.xml, reference/apcu/apcuiterator/gettotalsize.xml, reference/apcu/apcuiterator/key.xml, reference/apcu/apcuiterator/next.xml, reference/apcu/apcuiterator/rewind.xml, reference/apcu/apcuiterator/valid.xml, reference/apcu/book.xml, reference/apcu/functions/apcu-add.xml, reference/apcu/functions/apcu-cache-info.xml, reference/apcu/functions/apcu-cas.xml, reference/apcu/functions/apcu-clear-cache.xml, reference/apcu/functions/apcu-dec.xml, reference/apcu/functions/apcu-delete.xml, reference/apcu/functions/apcu-enabled.xml, reference/apcu/functions/apcu-entry.xml, reference/apcu/functions/apcu-exists.xml, reference/apcu/functions/apcu-fetch.xml, reference/apcu/functions/apcu-inc.xml, reference/apcu/functions/apcu-key-info.xml, reference/apcu/functions/apcu-sma-info.xml, reference/apcu/functions/apcu-store.xml, reference/apcu/ini.xml, reference/apcu/setup.xml
Translate apcuiterator.xml, book.xml, ini.xml and setup.xml in reference/apcu.
Translate all the files in reference/apcu/apcuiterators and reference/apcu/functions
The titles of the two first commits are not correct
The first one should be "Translate apcu/apcuiterator.xml"
The second one should be "Translate apcu/book.xml"
=> Translate the apcu extension in French

features/gc.xml
References  with "refcount" 1, are treated as if they are not references, so "is_ref" is "false" not "true"
=> Update gc.xml (FR version)

reference/mysqli/functions/mysqli-execute.xml, reference/solr/solrdocument/reset.xml, reference/solr/solrinputdocument/reset.xml, reference/solr/solrparams/add.xml, reference/solr/solrparams/get.xml, reference/solr/solrparams/set.xml, reference/xdiff/functions/xdiff-file-diff-binary.xml, reference/xdiff/functions/xdiff-file-patch-binary.xml, reference/xdiff/functions/xdiff-string-diff-binary.xml, reference/xdiff/functions/xdiff-string-patch-binary.xml
Minor changes, but I'm not sure about `reference/xdiff/functions/xdiff-file-diff-binary.xml`:
there was not `Alias de xdiff_file_bdiff` as expected, 
otherwise, the file seems to be up-to-date ([French](https://github.com/php/doc-fr/blob/master/reference/xdiff/functions/xdiff-file-diff-binary.xml) and [English](https://github.com/php/doc-en/blob/master/reference/xdiff/functions/xdiff-file-diff-binary.xml)) 🤔
=> Apply php/doc-en@bc0556b

language/types/type-juggling.xml
"à" -> "a"
"interpréter" -> "interprétée"
=> Corrected spelling mistake in french

reference/json/constants.xml
Infinitive tense is used instead of conjugating the word `récupérer`.
=> Fix. conjugaison in error description

appendices/migration80.xml, appendices/migration81.xml
I tried many things to avoid to have commit from previous PR ('Add migration help file for PHP8.0') even with help of @Girgias (probably became crazy thanks to me). I delete and recreate many times but impossible to have only the commit for migration81.xml, with my knoledge level of Git.
if someone has an explanation, I enjoy to read it.
Don't hesitate to contact me if necessary.
=> Add appendices migration81

language/types/type-juggling.xml
* "est ne sont pas" → "et ne sont pas"
* "sont identique" → "sont identiques"
* "et ne devrait pas être invoqué" → "vous ne devriez pas compter dessus" (rely on)
* "cast une variable" → "transtyper une variable"
* "Il n'est pas forcément évident ce qui se produira" → "Ce qui se produira n’est pas forcément évident"
* "un casting" → "un transtypage"
* "accès par caractères" → "accès par caractère" (by character, only one is possible)
* Removing of one duplicated paragraph.
=> type-juggling: fixes typo and litteral translation

language-snippets.ent, reference/pdo/pdo/prepare.xml
I stumbled upon a "Deplus" typo on the docs, so I thought that I might at least fix it (and find if there's more). So here it is, my (small) PR that fixes 2 typos, replacing "Deplus" strings by "De plus".
=> Typos: Deplus -> De plus

language/references.xml
- Add plural for _"leur**s** noms"_ and _"au**x** références"_
- remove _","_ According to me, we don't have _","_ before _"et"_ when we enumarate things. That was what I learn. It's maybe wrong ?
- Fix typo _"comm**e** expliqué"_
=> Fixing typo in references.xml

reference/strings/functions/implode.xml
Added "e" at the end of the word "supporté"
=> Corrected typo in implode.xml

language-defs.ent, language/functions.xml, language/types/string.xml, language/variables.xml, reference/exec/functions/proc-open.xml, reference/imap/functions/imap-mail-compose.xml, reference/mbstring/functions/mb-detect-encoding.xml, reference/network/functions/setcookie.xml, reference/pcre/pattern.syntax.xml, reference/pdo/pdo/quote.xml, reference/sqlsrv/functions/sqlsrv-close.xml, reference/strings/functions/strtok.xml, reference/zip/ziparchive/setexternalattributesname.xml
Hello,
I just searched all "example" typos in doc's and fixed them. Maybe i forgot some of them ?
Thanks for proofreading !
=> fix "example" typos

reference/datetime/datetime/settime.xml
Seems like someone used QWERTY keyboard to write french documentation 😉
=> Fix typo on setTime documentation

reference/pcre/pattern.modifiers.xml
As explained on #554 the current explanation for the "u" PCRE modifier says the opposite of what the modifier actually does. This rewords the whole paragraph the better to match the original english text.
=> Issue #554: reword explanation of PCRE modifier "u"

reference/sockets/functions/socket-create-pair.xml
PS : L'exemple dans la doc anglaise est déjà bon.
=> Fix socket-create-pair example, missing ')'

features/gc.xml, language-snippets.ent, reference/curl/functions/curl-getinfo.xml, reference/curl/functions/curl-share-setopt.xml, reference/event/eventbufferevent/connect.xml, reference/image/functions/imageaffinematrixget.xml, reference/memcache/memcache/add.xml, reference/oci8/functions/oci-connect.xml, reference/phar/PharData/setSignatureAlgorithm.xml, reference/session/functions/session-create-id.xml, reference/yaf/yaf-router.xml
Hi, fixed some typos:
déja => déjà
connection => connexion
clée => clé
parmi => parmis
Quick question, in `reference/curl/functions/curl-getinfo.xml` should we translate "handshake" ? (I saw "poignée de main" in 2 other files but it looks kinda weird)
=> Fix some typos

reference/array/functions/array-slice.xml
Although [last modification](https://github.com/php/doc-fr/commit/92ef1bfefc5ab464334909295f82bf8034b85d66) simplified the sentence to describe the behaviour of `array_slice` with `$length <0`, it changed its meaning.
> la séquence contiendra autant d'éléments de la fin du &array;
This is the opposite, the array will NOT contain elements at then end of the array! 
[Corresponding English documentation](https://github.com/php/doc-en/blob/9f30ccc6aa0dabe411c52305202fe85209ddc06b/reference/array/functions/array-slice.xml#L67-L68)
> the sequence will stop that many elements from the end of the array.
Nevertheless, I think this is a good idea to not translate literally here, so I propose to just replace `contiendra` by a verb with opposite sense: `exclura` (`exclude`) (but could also be …
=> Fix translation for array_slice length parameter

reference/pdo_mysql/constants.xml
In constants.xml used in https://www.php.net/manual/fr/ref.pdo-mysql.php, in the 'Exemple #1 Activation du mode non mis en cache de MySQL'section.A closing bracket is missing for the foreach loop, it may cause missing understanding for beginner in PHP.
=> Fix missing closing bracket

reference/dom/domchildnode/replacewith.xml
Add errors section to DOMChildNode's replaceWith method to fix parsing errors.
=> Fix domchildnode.replacewith parsing errors

reference/reflection/reflectionattribute.xml, reference/reflection/reflectionenum.xml, reference/reflection/reflectionenumbackedcase.xml, reference/reflection/reflectionenumunitcase.xml, reference/reflection/reflectionreference.xml
Here is my translation for the missing reflection classes : 
- `ReflectionAttribute`
- `ReflectionEnum`
- `ReflectionEnumBackedCase`
- `ReflectionEnumUnitCase`
- `ReflectionReference`
=> Add translation of missing reflection classes

reference/reflection/reflectionclass/isenum.xml, reference/reflection/reflectionclass/isreadonly.xml
Here is the translation of the missing `ReflectionClass` methods
- `ReflectionClass::isEnum()`
- `ReflectionClass::isReadOnly()`
=> Add translation of missing reflection class methods

reference/datetime/dateerror.xml, reference/datetime/dateexception.xml, reference/datetime/dateinvalidoperationexception.xml, reference/datetime/dateinvalidtimezoneexception.xml, reference/datetime/datemalformedintervalstringexception.xml, reference/datetime/datemalformedperiodstringexception.xml, reference/datetime/datemalformedstringexception.xml, reference/datetime/dateobjecterror.xml, reference/datetime/daterangeerror.xml
Here is the translation of missing date classes:
- `dateError`
- `dateException`
- `dateInvalidOperationException`
- `dateInvalidTimeZoneException`
- `dateMalformedIntervalStringException`
- `dateMalformedPeriodStringException`
- `dateMalformedStringException`
- `dateObjectError`
- `dateRangeError`
=> Translate date classes

reference/reflection/reflectionattribute.xml, reference/reflection/reflectionenum.xml, reference/reflection/reflectionenumbackedcase.xml, reference/reflection/reflectionenumunitcase.xml, reference/reflection/reflectionreference.xml
While browsing the PHP documentation tool website, I saw [this](http://doc.php.net/revcheck.php?p=misstags&lang=fr). 
This seems related to the missing `Status`.
(#800) My bad 😅
=> Fix missing en translation

reference/info/functions/assert.xml
I did the following changes:
- re indent some `<entry>` nodes
- remove the `<entry/>` node in the assert.bail section
Note: I did not test to see if it works. If needed I can try to test it with some help.
=> fix(assert): assert table configuration

reference/reflection/reflectionclassconstant/getattributes.xml, reference/reflection/reflectionclassconstant/isenumcase.xml, reference/reflection/reflectionclassconstant/isfinal.xml
Here is the translation of missing `ReflectionClassContant` methods
- `ReflectionClassContant::getAttributes()`
- `ReflectionClassContant::isEnumCase()`
- `ReflectionClassContant::isFinal()`
=> Translate missing `ReflectionClassConstant` methods

reference/math/functions/round.xml
BTW, `après le point décimal` should be `après la virgule` because in French the decimal separator is `,`
=> Translate digit (which was still in English)

reference/reflection/reflectionfiber/construct.xml, reference/reflection/reflectionfiber/getcallable.xml, reference/reflection/reflectionfiber/getexecutingfile.xml, reference/reflection/reflectionfiber/getexecutingline.xml, reference/reflection/reflectionfiber/getfiber.xml, reference/reflection/reflectionfiber/gettrace.xml
Here is the translation of missing `ReflectionFiber` methods
- `ReflectionFiber::__construct()`
- `ReflectionFiber::getCallable()`
- `ReflectionFiber::getExecutingFile()`
- `ReflectionFiber::getExecutingLine()`
- `ReflectionFiber::getFiber()`
- `ReflectionFiber::getTrace()`
=> Translate `ReflectionFiber` methods

reference/reflection/reflectionfunctionabstract/getattributes.xml, reference/reflection/reflectionfunctionabstract/getclosureusedvariables.xml, reference/reflection/reflectionfunctionabstract/gettentativereturntype.xml, reference/reflection/reflectionfunctionabstract/hastentativereturntype.xml
Here is the translation of missing `ReflectionFunctionAbstract` methods
- `ReflectionFunctionAbstract::getAttributes()`
- `ReflectionFunctionAbstract::getClosureUsedVariables()`
- `ReflectionFunctionAbstract::getTentativeReturnType()`
- `ReflectionFunctionAbstract::hasTentativeReturnType()`
=> Translate `ReflectionFunctionAbstract` methods

reference/reflection/reflectionreference/construct.xml, reference/reflection/reflectionreference/fromarrayelement.xml, reference/reflection/reflectionreference/getid.xml
Here is the translation of missing `ReflectionReference` methods
- `ReflectionReference::__construct()`
- `ReflectionReference::fromArrayElement()`
- `ReflectionReference::getId()`
This should be the lasts reference/reflection files :tada:
=> Translate `ReflectionReference` methods

language/predefined/closedgeneratorexception.xml, language/predefined/interfaces.xml, language/predefined/php-incomplete-class.xml, reference/var/functions/unserialize.xml
`ClosedGeneratorException` and `__PHP_Incomplete_Class`
See php/doc-en#3451 for related changes (revision checks were skipped).
=> Translate missing predefined files

reference/tokenizer/phptoken/construct.xml, reference/tokenizer/phptoken/getTokenName.xml, reference/tokenizer/phptoken/is.xml, reference/tokenizer/phptoken/isIgnorable.xml, reference/tokenizer/phptoken/toString.xml, reference/tokenizer/phptoken/tokenize.xml
Here is the translation of missing `PhpToken` methods
- `PhpToken::__construct()`
- `PhpToken::getTokenName()`
- `PhpToken::is()`
- `PhpToken::isIgnorable()`
- `PhpToken::tokenize()`
- `PhpToken::toString()`
=> Translate `PhpToken` methods

reference/mongodb/bson/binaryinterface.xml, reference/mongodb/bson/dbpointer.xml, reference/mongodb/bson/decimal128.xml, reference/mongodb/bson/decimal128interface.xml, reference/mongodb/bson/document.xml, reference/mongodb/bson/int64.xml, reference/mongodb/bson/iterator.xml, reference/mongodb/bson/javascriptinterface.xml, reference/mongodb/bson/maxkeyinterface.xml, reference/mongodb/bson/minkeyinterface.xml, reference/mongodb/bson/objectidinterface.xml, reference/mongodb/bson/packedarray.xml, reference/mongodb/bson/regexinterface.xml, reference/mongodb/bson/symbol.xml, reference/mongodb/bson/timestampinterface.xml, reference/mongodb/bson/undefined.xml, reference/mongodb/bson/utcdatetimeinterface.xml
Here is the translation of missing `MongoDB\Bson` stuf
- `MongoDB\Bson\BinaryInterface`
- `MongoDB\Bson\`DBPointer`
- `MongoDB\Bson\Decimal128`
- `MongoDB\Bson\Decimal128Interface`
- `MongoDB\Bson\Document`
- `MongoDB\Bson\Int64`
- `MongoDB\Bson\Iterator`
- `MongoDB\Bson\JavascriptInterface`
- `MongoDB\Bson\MaxKeInterface`
- `MongoDB\Bson\MinKeInterface`
- `MongoDB\Bson\ObjectIdInterface`
- `MongoDB\Bson\PackedArray`
- `MongoDB\Bson\RegexInterface`
- `MongoDB\Bson\Symbol`
- `MongoDB\Bson\TimestampInterface`
- `MongoDB\Bson\Undefined`
- `MongoDB\Bson\UtcDateTimeInterface`
=> Translate `MongoDB\BSON`

reference/mongodb/bson/document/construct.xml, reference/mongodb/bson/document/frombson.xml, reference/mongodb/bson/document/fromjson.xml, reference/mongodb/bson/document/fromphp.xml, reference/mongodb/bson/document/get.xml, reference/mongodb/bson/document/getiterator.xml, reference/mongodb/bson/document/has.xml, reference/mongodb/bson/document/offsetexists.xml, reference/mongodb/bson/document/offsetget.xml, reference/mongodb/bson/document/offsetset.xml, reference/mongodb/bson/document/offsetunset.xml, reference/mongodb/bson/document/serialize.xml, reference/mongodb/bson/document/tocanonicalextendedjson.xml, reference/mongodb/bson/document/tophp.xml, reference/mongodb/bson/document/torelaxedextendedjson.xml, reference/mongodb/bson/document/tostring.xml, reference/mongodb/bson/document/unserialize.xml
Here is the translation of missing `MongoDB\BSON\Document` methods
- `MongoDB\BSON\Document::__construct()`
- `MongoDB\BSON\Document::fromBSON()`
- `MongoDB\BSON\Document::fromJSON()`
- `MongoDB\BSON\Document::fromPHP()`
- `MongoDB\BSON\Document::get()`
- `MongoDB\BSON\Document::geIterator()`
- `MongoDB\BSON\Document::gas()`
- `MongoDB\BSON\Document::offsetExists()`
- `MongoDB\BSON\Document::offsetSet()`
- `MongoDB\BSON\Document::offetUnset()`
- `MongoDB\BSON\Document::serialize()`
- `MongoDB\BSON\Document::toCanonicalExtendedJson()`
- `MongoDB\BSON\Document::toPHP()`
- `MongoDB\BSON\Document::toRelaxedExtendedJson()`
- `MongoDB\BSON\Document::toString()`
- `MongoDB\BSON\Document::unserialize()`
=> Translate `MongoDB\BSON\Document`

reference/mongodb/bson/iterator/construct.xml, reference/mongodb/bson/iterator/current.xml, reference/mongodb/bson/iterator/key.xml, reference/mongodb/bson/iterator/next.xml, reference/mongodb/bson/iterator/rewind.xml, reference/mongodb/bson/iterator/valid.xml
Here is the translation of missing `MongoDB\BSON\Iterator` methods
- `MongoDB\BSON\Iterator::__construct()`
- `MongoDB\BSON\Iterator::current()`
- `MongoDB\BSON\Iterator::key()`
- `MongoDB\BSON\Iterator::next()`
- `MongoDB\BSON\Iterator::rewind()`
- `MongoDB\BSON\Iterator::valid()`
=> Translate `MongoDB\BSON\Iterator`

reference/mongodb/bson/packedarray/construct.xml, reference/mongodb/bson/packedarray/fromphp.xml, reference/mongodb/bson/packedarray/get.xml, reference/mongodb/bson/packedarray/getiterator.xml, reference/mongodb/bson/packedarray/has.xml, reference/mongodb/bson/packedarray/offsetexists.xml, reference/mongodb/bson/packedarray/offsetget.xml, reference/mongodb/bson/packedarray/offsetset.xml, reference/mongodb/bson/packedarray/offsetunset.xml, reference/mongodb/bson/packedarray/serialize.xml, reference/mongodb/bson/packedarray/tophp.xml, reference/mongodb/bson/packedarray/tostring.xml, reference/mongodb/bson/packedarray/unserialize.xml
Here is the translation of missing `MongoDB\BSON\PackedArray` methods
- `MongoDB\BSON\PackedArray::__construct()`
- `MongoDB\BSON\PackedArray::fromPHP()`
- `MongoDB\BSON\PackedArray::get()`
- `MongoDB\BSON\PackedArray::getIterator()`
- `MongoDB\BSON\PackedArray::offsetExists()`
- `MongoDB\BSON\PackedArray::offsetGet()`
- `MongoDB\BSON\PackedArray::offsetSet()`
- `MongoDB\BSON\PackedArray::offsetUnset()`
- `MongoDB\BSON\PackedArray::serialize()`
- `MongoDB\BSON\PackedArray::toPHP()`
- `MongoDB\BSON\PackedArray::toString()`
- `MongoDB\BSON\PackedArray::unserialize()`
=> Translate `MongoDB\BSON\PackedArray`

reference/com/compersisthelper/construct.xml, reference/com/compersisthelper/getcurfilename.xml, reference/com/compersisthelper/getmaxstreamsize.xml, reference/com/compersisthelper/initnew.xml, reference/com/compersisthelper/loadfromfile.xml, reference/com/compersisthelper/loadfromstream.xml, reference/com/compersisthelper/savetofile.xml, reference/com/compersisthelper/savetostream.xml
Here is the translation of missing `COMPersistHelper` methods
- `COMPersistHelper::__construct()`
- `COMPersistHelper::getCurFileName()`
- `COMPersistHelper::getMaxSteamSize()`
- `COMPersistHelper::initNew()`
- `COMPersistHelper::loadFromFile()`
- `COMPersistHelper::loadFromStream()`
- `COMPersistHelper::saveToFile()`
- `COMPersistHelper::saveToStream()`
=> Translate `COMPersistHelper` methods

reference/componere/componere/abstract/definition/addinterface.xml, reference/componere/componere/abstract/definition/addmethod.xml, reference/componere/componere/abstract/definition/addtrait.xml, reference/componere/componere/abstract/definition/getreflector.xml
Here is the translation of missing `Componere\Abstract\Definition` methods
- `Componere\Abstract\Definition::addInterface()`
- `Componere\Abstract\Definition::addMethod()`
- `Componere\Abstract\Definition::addTrait()`
- `Componere\Abstract\Definition::getReflector()`
=> Translate `Componere\Abstract\Definition` methods

reference/componere/componere/definition/addconstant.xml, reference/componere/componere/definition/addproperty.xml, reference/componere/componere/definition/construct.xml, reference/componere/componere/definition/getclosure.xml, reference/componere/componere/definition/getclosures.xml, reference/componere/componere/definition/isregistered.xml, reference/componere/componere/definition/register.xml
Here is the translation of missing `Componere\Definition` methods
- `Componere\Definition::addConstant()`
- `Componere\Definition::addProperty()`
- `Componere\Definition::__construct()`
- `Componere\Definition::getClosure()`
- `Componere\Definition::getClosures()`
- `Componere\Definition::isRegistered()`
- `Componere\Definition::register()`
=> Translate `Componere\Definition` methods

reference/componere/componere/method/construct.xml, reference/componere/componere/method/getreflector.xml, reference/componere/componere/method/setprivate.xml, reference/componere/componere/method/setprotected.xml, reference/componere/componere/method/setstatic.xml
Here is the translation of missing `Componere\Method` methods
- `Componere\Method::__construct()`
- `Componere\Method::getReflector()`
- `Componere\Method::setPrivate()`
- `Componere\Method::setProtected()`
- `Componere\Method::setStatic()`
=> Translate `Componere\Method` methods

reference/componere/componere/patch/apply.xml, reference/componere/componere/patch/construct.xml, reference/componere/componere/patch/derive.xml, reference/componere/componere/patch/getclosure.xml, reference/componere/componere/patch/getclosures.xml, reference/componere/componere/patch/isapplied.xml, reference/componere/componere/patch/revert.xml
Here is the translation of missing `Componere\Patch` methods
- `Componere\Patch::apply()`
- `Componere\Patch::__construct()`
- `Componere\Patch::derive()`
- `Componere\Patch::getClosure()`
- `Componere\Patch::getClosures()`
- `Componere\Patch::isApplied()`
- `Componere\Patch::revert()`
=> Translate `Componere\Patch` methods

reference/componere/componere/value/construct.xml, reference/componere/componere/value/hasdefault.xml, reference/componere/componere/value/isprivate.xml, reference/componere/componere/value/isprotected.xml, reference/componere/componere/value/isstatic.xml, reference/componere/componere/value/setprivate.xml, reference/componere/componere/value/setprotected.xml, reference/componere/componere/value/setstatic.xml
Here is the translation of missing `Componoere\Value` methods
- `Componoere\Value::__construct()`
- `Componoere\Value::hasDefault()`
- `Componoere\Value::isPrivate()`
- `Componoere\Value::isProtected()`
- `Componoere\Value::isStatic()`
- `Componoere\Value::setPrivate()`
- `Componoere\Value::setProtected()`
- `Componoere\Value::setStatic()`
=> Translate `Componoere\Value` methods

reference/dom/domnamednodemap/getiterator.xml, reference/dom/domnode/contains.xml, reference/dom/domnode/getrootnode.xml, reference/dom/domnode/isequalnode.xml, reference/dom/domnodelist/getiterator.xml, reference/dom/domparentnode/replacechildren.xml
Translation of
- `DOMNamedNodeMap::getIterator()`
- `DOMNode::contains()`
- `DOMNode::getRootNode()`
- `DOMNode::isEqualNode()`
- `DOMNodeList::getIterator()`
- `DOMParentNode::replaceChildren()`
=> Translate `Dom\*node*` methods

reference/dom/domdocument/adoptnode.xml, reference/dom/domdocument/append.xml, reference/dom/domdocument/prepend.xml, reference/dom/domdocument/replacechildren.xml, reference/dom/domdocumentfragment/append.xml, reference/dom/domdocumentfragment/prepend.xml, reference/dom/domdocumentfragment/replacechildren.xml
Here is the translation of missing `DomDocument*` methods
- `DomDocument::adoptNode()`
- `DomDocument::append()`
- `DomDocument::preprend()`
- `DomDocument::replaceChildren()`
And
- `DOMDocumentFragment::append()`
- `DOMDocumentFragment::prepend()`
- `DOMDocumentFragment::replaceChildren()`
=> Translate `DomDocument*\` methods

reference/dom/domelement/after.xml, reference/dom/domelement/append.xml, reference/dom/domelement/before.xml, reference/dom/domelement/getattributenames.xml, reference/dom/domelement/insertadjacentelement.xml, reference/dom/domelement/insertadjacenttext.xml, reference/dom/domelement/prepend.xml, reference/dom/domelement/remove.xml, reference/dom/domelement/replacechildren.xml, reference/dom/domelement/replacewith.xml, reference/dom/domelement/toggleattribute.xml
Here is the translation of missing `DOMElement` methods
- `DOMElement::after()`
- `DOMElement::append()`
- `DOMElement::getAttributeNames()`
- `DOMElement::insertAdjancentElement()`
- `DOMElement::insertAdjacentText()`
- `DOMElement::remove()`
- `DOMElement::replaceChildren()`
- `DOMElement::replaceWith()`
- `DOMElement::toggleAttribute()`
=> Translate `DOMElement` methods

reference/mongodb/mongodb/driver/bulkwrite/construct.xml, reference/mongodb/mongodb/driver/bulkwrite/count.xml, reference/mongodb/mongodb/driver/bulkwrite/delete.xml, reference/mongodb/mongodb/driver/bulkwrite/insert.xml, reference/mongodb/mongodb/driver/bulkwrite/update.xml
Here is the translation of missing `MongoDB\Driver\BulkWrite` methods
- `MongoDB\Driver\BulkWrite::__construct()`
- `MongoDB\Driver\BulkWrite::count()`
- `MongoDB\Driver\BulkWrite::delete()`
- `MongoDB\Driver\BulkWrite::insert()`
- `MongoDB\Driver\BulkWrite::update()`
=> Translate `MongoDB\Driver\BulkWrite` methods

reference/mongodb/mongodb/driver/clientencryption/addkeyaltname.xml, reference/mongodb/mongodb/driver/clientencryption/construct.xml, reference/mongodb/mongodb/driver/clientencryption/createdatakey.xml, reference/mongodb/mongodb/driver/clientencryption/decrypt.xml, reference/mongodb/mongodb/driver/clientencryption/deletekey.xml, reference/mongodb/mongodb/driver/clientencryption/encrypt.xml, reference/mongodb/mongodb/driver/clientencryption/encryptexpression.xml, reference/mongodb/mongodb/driver/clientencryption/getkey.xml, reference/mongodb/mongodb/driver/clientencryption/getkeybyaltname.xml, reference/mongodb/mongodb/driver/clientencryption/getkeys.xml, reference/mongodb/mongodb/driver/clientencryption/removekeyaltname.xml, reference/mongodb/mongodb/driver/clientencryption/rewrapmanydatakey.xml
Here is the translation of missing `MongoDB\Driver\ClientEncryption` methods
- `MongoDB\Driver\ClientEncryption::addKeyAltName()`
- `MongoDB\Driver\ClientEncryption::__construct()`
- `MongoDB\Driver\ClientEncryption::createDataKey()`
- `MongoDB\Driver\ClientEncryption::decrypt()`
- `MongoDB\Driver\ClientEncryption::deleteKey()`
- `MongoDB\Driver\ClientEncryption::encrypt()`
- `MongoDB\Driver\ClientEncryption::encrypExpression()`
- `MongoDB\Driver\ClientEncryption::getKey()`
- `MongoDB\Driver\ClientEncryption::getKeyByAltName()`
- `MongoDB\Driver\ClientEncryption::getKeys()`
- `MongoDB\Driver\ClientEncryption::removeKeyAltName()`
- `MongoDB\Driver\ClientEncryption::rewrapManyDataKey()`
=> Translate `MongoDB\Driver\ClientEncryption`

reference/zookeeper/zookeeper/addauth.xml, reference/zookeeper/zookeeper/close.xml, reference/zookeeper/zookeeper/connect.xml, reference/zookeeper/zookeeper/construct.xml, reference/zookeeper/zookeeper/create.xml, reference/zookeeper/zookeeper/delete.xml, reference/zookeeper/zookeeper/exists.xml, reference/zookeeper/zookeeper/get.xml, reference/zookeeper/zookeeper/getacl.xml, reference/zookeeper/zookeeper/getchildren.xml, reference/zookeeper/zookeeper/getclientid.xml, reference/zookeeper/zookeeper/getconfig.xml, reference/zookeeper/zookeeper/getrecvtimeout.xml, reference/zookeeper/zookeeper/getstate.xml, reference/zookeeper/zookeeper/isrecoverable.xml, reference/zookeeper/zookeeper/set.xml, reference/zookeeper/zookeeper/setacl.xml, reference/zookeeper/zookeeper/setdebuglevel.xml, reference/zookeeper/zookeeper/setdeterministicconnorder.xml, reference/zookeeper/zookeeper/setlogstream.xml, reference/zookeeper/zookeeper/setwatcher.xml
Here is the translation of missing `Zookeeper\Zookeepe` methods
- `Zookeeper\ZooKeeper::addauth()`
- `Zookeeper\ZooKeeper::close()`
- `Zookeeper\ZooKeeper::connect()`
- `Zookeeper\ZooKeeper::construct()`
- `Zookeeper\ZooKeeper::create()`
- `Zookeeper\ZooKeeper::delete()`
- `Zookeeper\ZooKeeper::exists()`
- `Zookeeper\ZooKeeper::get()`
- `Zookeeper\ZooKeeper::getAcl()`
- `Zookeeper\ZooKeeper::getChildren()`
- `Zookeeper\ZooKeeper::getClientid()`
- `Zookeeper\ZooKeeper::getConfig()`
- `Zookeeper\ZooKeeper::getRecvtimeout()`
- `Zookeeper\ZooKeeper::getState()`
- `Zookeeper\ZooKeeper::isRecoverable()`
- `Zookeeper\ZooKeeper::set()`
- `Zookeeper\ZooKeeper::setAcl()`
- `Zookeeper\ZooKeeper::setDebugLevel()`
- `Zookeeper\ZooKeeper::setDeterministicConnorder()`
- …
=> Translate `Zookeeper\Zookeeper`

reference/imagick/imagickkernel/addkernel.xml, reference/imagick/imagickkernel/addunitykernel.xml, reference/imagick/imagickkernel/frombuiltin.xml, reference/imagick/imagickkernel/frommatrix.xml, reference/imagick/imagickkernel/getmatrix.xml, reference/imagick/imagickkernel/scale.xml, reference/imagick/imagickkernel/separate.xml
Here is the translation of missing `Imagick\ImagickKernel` methods
- `Imagick\ImagickKernel::addKernel()`
- `Imagick\ImagickKernel::addUnityKernel()`
- `Imagick\ImagickKernel::fromBuiltIn()`
- `Imagick\ImagickKernel::fromMatrix()`
- `Imagick\ImagickKernel::getMatrix()`
- `Imagick\ImagickKernel::scale()`
- `Imagick\ImagickKernel::separate()`
=> Translate `Imagick\ImagickKernel`

reference/intl/intltimezone/construct.xml, reference/intl/intltimezone/createtimezoneidenumeration.xml, reference/intl/intltimezone/getidforwindowsid.xml, reference/intl/intltimezone/getregion.xml, reference/intl/intltimezone/getunknown.xml, reference/intl/intltimezone/getwindowsid.xml
Here is the translation of missing `IntlTimeZone` methods
- `IntlTimeZone::__construct()`
- `IntlTimeZone::createTimeZoneIdEnumeration()`
- `IntlTimeZone::getIdForWindowsId()`
- `IntlTimeZone::getRegion()`
- `IntlTimeZone::getUnknown()`
- `IntlTimeZone::getWindowsId()`
=> Translate `IntlTimeZone`

reference/luasandbox/luasandboxfunction/call.xml, reference/luasandbox/luasandboxfunction/construct.xml, reference/luasandbox/luasandboxfunction/dump.xml
Here is the translation of missing `LuaSandboxFunctions` methods
- `LuaSandboxFunctions::call()`
- `LuaSandboxFunctions::__construct()`
- `LuaSandboxFunctions::dump()`
=> Translate `LuaSandboxFunctions` methods

reference/mongodb/mongodb/driver/monitoring/commandsubscriber/commandfailed.xml, reference/mongodb/mongodb/driver/monitoring/commandsubscriber/commandstarted.xml, reference/mongodb/mongodb/driver/monitoring/commandsubscriber/commandsucceeded.xml
Here is the translation of missing `MongoDB\Driver\Monitoring\CommandSubscriber` methods
- `MongoDB\Driver\Monitoring\CommandSubscriber::commandFailed()`
- `MongoDB\Driver\Monitoring\CommandSubscriber::commandStarted()`
- `MongoDB\Driver\Monitoring\CommandSubscriber::commandSucceeded()`
=> Translate `MongoDB\Driver\Monitoring\CommandSubscriber` methods

reference/mongodb/mongodb/driver/manager/addsubscriber.xml, reference/mongodb/mongodb/driver/manager/construct.xml, reference/mongodb/mongodb/driver/manager/createclientencryption.xml, reference/mongodb/mongodb/driver/manager/executebulkwrite.xml, reference/mongodb/mongodb/driver/manager/executecommand.xml, reference/mongodb/mongodb/driver/manager/executequery.xml, reference/mongodb/mongodb/driver/manager/executereadcommand.xml, reference/mongodb/mongodb/driver/manager/executereadwritecommand.xml, reference/mongodb/mongodb/driver/manager/executewritecommand.xml, reference/mongodb/mongodb/driver/manager/getencryptedfieldsmap.xml, reference/mongodb/mongodb/driver/manager/getreadconcern.xml, reference/mongodb/mongodb/driver/manager/getreadpreference.xml, reference/mongodb/mongodb/driver/manager/getwriteconcern.xml, reference/mongodb/mongodb/driver/manager/removesubscriber.xml, reference/mongodb/mongodb/driver/manager/selectserver.xml, reference/mongodb/mongodb/driver/manager/startsession.xml
Here is the translation of missing `MongoDB\Driver\Manager` methods
- `MongoDB\Driver\Manager::addSubcriber()`
- `MongoDB\Driver\Manager::__construct()`
- `MongoDB\Driver\Manager::createClientEncryption()`
- `MongoDB\Driver\Manager::executeBulkWrite()`
- `MongoDB\Driver\Manager::executeCommand()`
- `MongoDB\Driver\Manager::executeQuery()`
- `MongoDB\Driver\Manager::executeReadCommand()`
- `MongoDB\Driver\Manager::executeReadWriteCommand()`
- `MongoDB\Driver\Manager::executeWriteCommand()`
- `MongoDB\Driver\Manager::getEncryptedFieldsMap()`
- `MongoDB\Driver\Manager::getReadConcern()`
- `MongoDB\Driver\Manager::getReadPreference()`
- `MongoDB\Driver\Manager::getWriteConcern()`
- `MongoDB\Driver\Manager::removeSubscriber()`
- `MongoDB\Driver\Manager::selectServer()`
- …
=> Translate `MongoDB\Driver\Manager`

reference/mongodb/mongodb/driver/monitoring/topologychangedevent/getnewdescription.xml, reference/mongodb/mongodb/driver/monitoring/topologychangedevent/getpreviousdescription.xml, reference/mongodb/mongodb/driver/monitoring/topologychangedevent/gettopologyid.xml, reference/mongodb/mongodb/driver/monitoring/topologyclosedevent/gettopologyid.xml, reference/mongodb/mongodb/driver/monitoring/topologyopeningevent/gettopologyid.xml
Here is the translation of `MongoDB\Driver\Monitoring\Topology*Event` methods
- `MongoDB\Driver\Monitoring\TopologyChangedEvent`:
- `MongoDB\Driver\Monitoring\TopologyChangedEvent::getNewDescription()`
- `MongoDB\Driver\Monitoring\TopologyChangedEvent::getPreviousDescription()`
- `MongoDB\Driver\Monitoring\TopologyChangedEvent::getTopologyid()`
- `MongoDB\Driver\Monitoring\TopologyClosedEvent`:
- `MongoDB\Driver\Monitoring\TopologyClosedEvent::getTopologyid()`
- `MongoDB\Driver\Monitoring\TopologyOpeningEvent`:
- `MongoDB\Driver\Monitoring\TopologyOpeningEvent::getTopologyid()`
=> Translate `MongoDB\Driver\Monitoring\Topology*Event`

reference/mongodb/mongodb/driver/server/executereadcommand.xml, reference/mongodb/mongodb/driver/server/executereadwritecommand.xml, reference/mongodb/mongodb/driver/server/executewritecommand.xml, reference/mongodb/mongodb/driver/server/getserverdescription.xml, reference/mongodb/mongodb/driver/server/gettags.xml, reference/mongodb/mongodb/driver/server/isarbiter.xml, reference/mongodb/mongodb/driver/server/ishidden.xml, reference/mongodb/mongodb/driver/server/isprimary.xml, reference/mongodb/mongodb/driver/server/issecondary.xml
Here is the translation of missing `MongoDB\Driver\Server` methods
- `MongoDB\Driver\Server::executeReadCommand()`
- `MongoDB\Driver\Server::executeReadWriteCommand()`
- `MongoDB\Driver\Server::executeWriteCommand()`
- `MongoDB\Driver\Server::getServerDescription()`
- `MongoDB\Driver\Server::getTags()`
- `MongoDB\Driver\Server::isArbiter()`
- `MongoDB\Driver\Server::isHidden()`
- `MongoDB\Driver\Server::isPrimary()`
- `MongoDB\Driver\Server::isSecondary()`
=> Translate `MongoDB\Driver\Server`

reference/mongodb/mongodb/driver/serverapi/bsonserialize.xml, reference/mongodb/mongodb/driver/serverapi/construct.xml, reference/mongodb/mongodb/driver/serverapi/serialize.xml, reference/mongodb/mongodb/driver/serverapi/unserialize.xml
Here is the translation of missing `MongoDB\Driver\ServerApi` methods
- `MongoDB\Driver\ServerApi::bsonSerializ`
- `MongoDB\Driver\ServerApi::__construct()`
- `MongoDB\Driver\ServerApi::serialize`
- `MongoDB\Driver\ServerApi::unserialize`
=> Translate `MongoDB\Driver\ServerApi`

reference/mongodb/mongodb/driver/session/aborttransaction.xml, reference/mongodb/mongodb/driver/session/advanceclustertime.xml, reference/mongodb/mongodb/driver/session/advanceoperationtime.xml, reference/mongodb/mongodb/driver/session/committransaction.xml, reference/mongodb/mongodb/driver/session/construct.xml, reference/mongodb/mongodb/driver/session/endsession.xml, reference/mongodb/mongodb/driver/session/getclustertime.xml, reference/mongodb/mongodb/driver/session/getlogicalsessionid.xml, reference/mongodb/mongodb/driver/session/getoperationtime.xml, reference/mongodb/mongodb/driver/session/getserver.xml, reference/mongodb/mongodb/driver/session/gettransactionoptions.xml, reference/mongodb/mongodb/driver/session/gettransactionstate.xml, reference/mongodb/mongodb/driver/session/isdirty.xml, reference/mongodb/mongodb/driver/session/isintransaction.xml, reference/mongodb/mongodb/driver/session/starttransaction.xml
Here is the translation of missing `MongoDB\Driver\Session` methods
- `MongoDB\Driver\Session::abortTransaction()`
- `MongoDB\Driver\Session::advanceClusterTime()`
- `MongoDB\Driver\Session::advanceOperationTime()`
- `MongoDB\Driver\Session::commitTransaction()`
- `MongoDB\Driver\Session::__construct()`
- `MongoDB\Driver\Session::endSession()`
- `MongoDB\Driver\Session::getClusterTime()`
- `MongoDB\Driver\Session::getLogicalSessionId()`
- `MongoDB\Driver\Session::getOperationTime()`
- `MongoDB\Driver\Session::getServer()`
- `MongoDB\Driver\Session::getTransactionOptions()`
- `MongoDB\Driver\Session::getTransactionState()`
- `MongoDB\Driver\Session::isDirty()`
- `MongoDB\Driver\Session::isInTransaction()`
- `MongoDB\Driver\Session::startTransaction()`
=> Translate `MongoDB\Driver\Session`

reference/mongodb/mongodb/driver/topologydescription/getservers.xml, reference/mongodb/mongodb/driver/topologydescription/gettype.xml, reference/mongodb/mongodb/driver/topologydescription/hasreadableserver.xml, reference/mongodb/mongodb/driver/topologydescription/haswritableserver.xml
Here is the translation of missing `MongoDB\Driver\TopologyDescription` methods
- `MongoDB\Driver\TopologyDescription::getServers()`
- `MongoDB\Driver\TopologyDescription::getType()`
- `MongoDB\Driver\TopologyDescription::hasReadableServer()`
- `MongoDB\Driver\TopologyDescription::hasWritableServer()`
=> Translate `MongoDB\Driver\TopologyDescription`

reference/spl/splfixedarray/getiterator.xml, reference/spl/splfixedarray/jsonserialize.xml, reference/spl/splfixedarray/serialize.xml, reference/spl/splfixedarray/unserialize.xml
Here is the translation of missing `SplFixedArray` methods
- `SplFixedArray::getIterator()`
- `SplFixedArray::jsonSerializer()`
- `SplFixedArray::__serialize()`
- `SplFixedArray::__unserialize()`
=> Translate missing `SplFixedArray` methods

reference/strings/functions/str-getcsv.xml
Fixed a small typo (`échappé` instead of `échapper`), and tried to clarify the meaning by moving `à l'intérieur d'un champ` earlier in the sentence.
What do you think? 🙂
=> Typo in str_getcsv description

reference/curl/constants_curl_setopt.xml
Sync `curl_set_opt` with en
Remove some useless spaces
=> Sync `curl_set_opt` with en

reference/reflection/reflectionclass/getlazyinitializer.xml, reference/reflection/reflectionclass/initializelazyobject.xml, reference/reflection/reflectionclass/isuninitializedlazyobject.xml, reference/reflection/reflectionclass/marklazyobjectasinitialized.xml, reference/reflection/reflectionclass/newlazyghost.xml, reference/reflection/reflectionclass/newlazyproxy.xml, reference/reflection/reflectionclass/resetaslazyghost.xml, reference/reflection/reflectionclass/resetaslazyproxy.xml
Here is the translation of new `ReflectionClass` methods
- `ReflectionClass::getLazyInitializer()`
- `ReflectionClass::initializeLazyObject()`
- `ReflectionClass::isUninitializedLazyObject()`
- `ReflectionClass::markLazyObjectAsInitialized()` 
- `ReflectionClass::newLazyGhost()`
- `ReflectionClass::newLazyProxy()`
- `ReflectionClass::resetAsLazyGhost()`
- `ReflectionClass::resetAsLazyProxy()`
=> Translate missing `ReflectionClass` methods

reference/xpass/constants.xml
See #1984
(https://doc.php.net/revcheck.php?p=misstags&lang=fr)
=> Add missing hash revision on `xpass/constants`

language/attributes.xml, language/basic-syntax.xml, language/constants.xml, language/context.xml, language/control-structures.xml, language/enumerations.xml, language/exceptions.xml, language/expressions.xml, language/functions.xml, language/namespaces.xml, language/references.xml, language/variables.xml, security/database.xml, security/errors.xml, security/intro.xml, security/variables.xml
This pull request includes various minor corrections to grammar and spelling in multiple XML files. The changes are primarily focused on improving the readability and accuracy of the documentation.
Grammar and spelling corrections:
* [`language/attributes.xml`](diffhunk://#diff-1fcbf18c6657f80597db4568e84912c4a08e2d8cdb94c0dd7ab7d68d36099332L25-R25): Removed redundant word "sur".
* [`language/basic-syntax.xml`](diffhunk://#diff-d0dcc4ce9ad6b405ca06df40b714aaaa5ff3a33ac53000421aa7bc03ca195e53L104-R104): Corrected the spelling of "afficher" to "affiché".
* [`language/constants.xml`](diffhunk://#diff-3a9bc46559c78a908f5564fbc8c8c2f8c4cfa82dc128697750346102db19b719L122-R122): Corrected the phrase "en tous cas" to "en tout cas".
* [`language/context.xml`](diffhunk://#diff-fa6468b6f7acb5fb5fc16a …
=> fix wording grammar folder security and language

language/context/ssl.xml, language/context/zip.xml, language/control-structures/break.xml, language/control-structures/for.xml, language/control-structures/return.xml, language/control-structures/switch.xml
This pull request includes several corrections and improvements to the French language documentation files. The most important changes involve fixing grammatical errors and improving the accuracy of translations.
Grammatical corrections:
* [`language/context/ssl.xml`](diffhunk://#diff-72d51ea12d82a7932d0d7c631c414a7f2260b8fd6ea9ce20d270d01fa81b75adL185-R185): Corrected a grammatical error in the description of the `peer_certificate` context option.
* [`language/context/zip.xml`](diffhunk://#diff-449acc17af0e27af7273a30836a4c170dc453f0c0ac1236ac48ab07596960806L29-R29): Fixed grammatical errors in the description and example for specifying a password for encrypted archives. [[1]](diffhunk://#diff-449acc17af0e27af7273a30836a4c170dc453f0c0ac1236ac48ab07596960806L29-R29) …
=> fix wording grammar folder control structures and context

reference/spl/arrayobject/construct.xml
This pull request includes updates to the `reference/spl/arrayobject/construct.xml` file to reflect recent changes in the documentation. The most important changes include updating the revision reference and clarifying the description of the class requirements for `ArrayObject` iterations.
Documentation updates:
* Updated the revision reference to `65c558143647fe63b8073180ba314067d5ea4b62`.
* Clarified that the class used for `ArrayObject` iterations must be a subtype of `ArrayIterator`.
=> update array object construct doc en

reference/bc/bcmath/number/round.xml
This pull request includes updates to the `reference/bc/bcmath/number/round.xml` file to enhance the documentation for the `round` function. The most important changes include updating the revision ID and improving the description of the `mode` parameter.
Documentation updates:
* Updated the revision ID in the XML header to reflect the latest changes.
* Improved the description of the `mode` parameter by specifying that it refers to the rounding mode and providing a reference to `RoundingMode` for more information.
=> update round.xml doc en

reference/pcntl/functions/pcntl-waitpid.xml
Fix #1950
This pull request includes updates to the `reference/pcntl/functions/pcntl-waitpid.xml` file to improve the clarity and accuracy of the documentation for the `pcntl_waitpid` function. The changes focus on refining the descriptions of the function's behavior based on different `process_id` values.
Documentation improvements:
* Updated the description for `< -1` to specify that it waits for a child process with a group ID equal to the absolute value of `process_id`.
* Clarified the description for `-1` to indicate it waits for any child process, aligning it with the behavior of `pcntl_wait`.
* Refined the description for `0` to state it waits for a child process with a group ID equal to that of the current process.
* Improved the description for `> 0` to specify it waits for the …
=> fix wording translate page pcntl-waitpid

reference/math/functions/round.xml
This pull request includes updates to the `reference/math/functions/round.xml` file to enhance the documentation for the `round` function. The changes focus on updating the parameter types, adding new rounding modes, and providing more detailed examples.
Key changes include:
* Updated the `mode` parameter to accept both `int` and `RoundingMode` types, with a new default value of `RoundingMode::HalfAwayFromZero`.
* Added a note to specify that some newly added rounding modes are only available in the `RoundingMode` enumeration.
* Included a new entry in the changelog to document the addition of four new rounding modes in version 8.4.0.
* Added a comprehensive example demonstrating the usage of the `RoundingMode` enumeration with various rounding modes and their effects on different …
=> update reference math round doc en

appendices/ini.core.xml, language/oop5/late-static-bindings.xml, reference/funchand/functions/register-tick-function.xml, reference/image/functions/getimagesize.xml, security/sessions.xml
This pull request includes several updates to XML documentation files to improve clarity and accuracy. The changes primarily involve updates to descriptions, code formatting, and examples.
* [`appendices/ini.core.xml`](diffhunk://#diff-d073e8bdff903d42517ff1661208a48b607c5172f67081218345872d5476c244L215-R218): Updated the description of directives related to disabling functions and classes, including details about changes in behavior starting from PHP 8.0.0. [[1]](diffhunk://#diff-d073e8bdff903d42517ff1661208a48b607c5172f67081218345872d5476c244L215-R218) [[2]](diffhunk://#diff-d073e8bdff903d42517ff1661208a48b607c5172f67081218345872d5476c244L237-R241)
* [`language/oop5/late-static-bindings.xml`](diffhunk://#diff-e3ad26513ce477b0c5789dd457164fef034e8f4815d1b2ba309af2d9dabe3a9bL52-R74): …
=> sync doc php en

appendices/resources.xml, language/predefined/iteratoraggregate/getiterator.xml, reference/reflection/book.xml, reference/reflection/reflectionproperty/ispublic.xml
This pull request includes several changes to XML files within the documentation. The changes involve updating revision comments, modifying descriptions, and adding new sections for clarity. The most important changes are listed below:
* Updated the revision comment and description for `IteratorAggregate::getIterator` to include that it returns an external iterator or a traversable object. (`language/predefined/iteratoraggregate/getiterator.xml`) [[1]](diffhunk://#diff-832a29f52c2970ba59e774ad21a7516a326bc27cdd102fde8abdfc7d5888167bL2-R7) [[2]](diffhunk://#diff-832a29f52c2970ba59e774ad21a7516a326bc27cdd102fde8abdfc7d5888167bL17-R17)
* Modified the column width in the table within `appendices/resources.xml` to improve layout. (`appendices/resources.xml`)
* Added a new reference to …
=> update EN revision number

.github/workflows/integrate.yaml
This pull request includes an update to the `.github/workflows/integrate.yaml` file to ensure compatibility with the latest Ubuntu version.
Issue:  [https://github.com/actions/runner-images/issues/11101](https://github.com/actions/runner-images/issues/11101)
* [`.github/workflows/integrate.yaml`](diffhunk://#diff-d684acc09c646fd347d0ee93598101fb403664cc70e38cb6f671355ab6de1854L15-R15): Updated the `runs-on` parameter from "ubuntu-20.04" to "ubuntu-22.04" to use the latest Ubuntu version for the build process.
=> update workflow integrate yaml ubuntu

reference/pdo_sqlite/pdo/sqlite/loadextension.xml, reference/pdo_sqlite/pdo/sqlite/openblob.xml
This pull request includes the addition of two new XML reference files for the `Pdo\Sqlite` class, documenting the `loadExtension` and `openBlob` methods. These files provide detailed descriptions, parameters, return values, errors, examples, notes, and related methods.
Documentation for `Pdo\Sqlite` methods:
* [`reference/pdo_sqlite/pdo/sqlite/loadextension.xml`](diffhunk://#diff-1600ccfa44c8ee61a1a96b6cf2a1faf8236d58b7628a85a766ef21233e98505fR1-R113): Added a reference entry for the `Pdo\Sqlite::loadExtension` method, including descriptions, parameters, return values, errors, examples, notes, and related methods.
* [`reference/pdo_sqlite/pdo/sqlite/openblob.xml`](diffhunk://#diff-93b42d98f6cfdd73640b34726d036fd7f0405715f10704028cdc62d12c644cdcR1-R149): Added a reference entry for the …
=> add translate new page pdo_sqlite
