reference/filter/filters.xml

Fix some french typos

---

language/oop5/interfaces.xml

`classe` is feminine so the pronoun must be `la` and not `le`

Fix a pronoun error

---

reference/url/functions/base64-decode.xml

Just 2 typos, and a little bit of rephrasing to disambiguate to which of the 2 "if"s the "else" belonged: "Si ... si ... sinon ..." wasn't absolutely clear at first reading.

 Update base64-decode.xml

---

reference/sqlite3/sqlite3/createfunction.xml

Actually fixing issue mentioned in #47

Fix constant name

---

language/functions.xml
reference/errorfunc/functions/error-log.xml
reference/mysqli/mysqli/construct.xml
reference/pdo/pdo/construct.xml
reference/reflection/reflectionclass/getconstants.xml
reference/reflection/reflectionclass/getreflectionconstants.xml

This PR propose fixing multiple usage of the same error "peut importe" instead of "peu importe". I also fixed and changed a few minor issues around the above mentionned spelling error.

fix some spelling

---

appendices/reserved.constants.core.xml

Correction des valeurs d'exemple

Correction exemple PHP_MINOR_VERSION et PHP_RELEASE_VERSION

---

reference/pthreads/cond/broadcast.xml
reference/pthreads/cond/destroy.xml
reference/pthreads/cond/signal.xml
reference/pthreads/cond/wait.xml
reference/pthreads/mutex/destroy.xml
reference/pthreads/mutex/lock.xml
reference/pthreads/mutex/trylock.xml
reference/pthreads/mutex/unlock.xml
reference/pthreads/pool/resize.xml
reference/pthreads/pool/shutdown.xml
reference/pthreads/thread/isjoined.xml
reference/pthreads/thread/isstarted.xml
reference/pthreads/thread/join.xml
reference/pthreads/thread/kill.xml
reference/pthreads/thread/start.xml
reference/pthreads/threaded/extend.xml
reference/pthreads/threaded/merge.xml
reference/pthreads/threaded/notify.xml
reference/pthreads/threaded/unlock.xml
reference/pthreads/threaded/wait.xml
reference/pthreads/worker/shutdown.xml

Apply php/doc-en@7febeefab69aa2920922de7adfe17724148d0b60

Updated pthreads section

---

reference/solr/solrinputdocument/setfieldboost.xml
reference/solr/solrquery/sethighlightformatter.xml
reference/solr/solrquery/sethighlightsimplepost.xml

Apply php/doc-en@d00128a85a6c2e8e5ae4545fdd23368df8cfa079

Updated to en-revision

---

language/basic-syntax.xml

Translated a part of the text which hadn't been yet.

Fixed missing untranslated text

---

reference/url/functions/rawurlencode.xml

Fixed cut sentence

---

reference/zlib/book.xml

Based on this diff http://doc.php.net/revcheck.php?p=plain&lang=fr&hbp=5f8047c12b4078a6f686b2b0589e9284c47bf155&f=reference/zlib/book.xml&c=on

Update reference/zlib/book to English revision

---

reference/var/functions/unset.xml

Based on this diff: http://doc.php.net/revcheck.php?p=plain&lang=fr&hbp=9e0f03ac354d797d1d16c0fcc1663e5e170f2727&f=reference/var/functions/unset.xml&c=on

Update reference/var/functions/unset to English revision

---

reference/strings/functions/str-getcsv.xml

Based on diff: http://doc.php.net/revcheck.php?p=plain&lang=fr&hbp=e095023e408c8cb6378ae16bb6870343a3946919&f=reference/strings/functions/str-getcsv.xml&c=on

Update reference/strings/functions/str-getcsv to English revision

---

language-snippets.ent
reference/datetime/functions/date-sunrise.xml
reference/datetime/functions/date-sunset.xml
reference/datetime/functions/strptime.xml
reference/image/functions/imagefilledpolygon.xml
reference/image/functions/imageopenpolygon.xml
reference/image/functions/imagepolygon.xml
reference/imap/constants.xml
reference/mhash/functions/mhash-count.xml
reference/mhash/functions/mhash-get-block-size.xml
reference/mhash/functions/mhash-get-hash-name.xml
reference/mhash/functions/mhash-keygen-s2k.xml
reference/mhash/functions/mhash.xml
reference/oci8/ini.xml
reference/pdo/constants.xml
reference/uodbc/functions/odbc-result-all.xml

Deprecated functions and constants

Apply commit 8a2141dcc084f72feb4e0ae2feaff3b440e5c59e

---

appendices/resources.xml
language-snippets.ent
reference/pspell/book.xml
reference/pspell/functions/pspell-add-to-personal.xml
reference/pspell/functions/pspell-add-to-session.xml
reference/pspell/functions/pspell-check.xml
reference/pspell/functions/pspell-clear-session.xml
reference/pspell/functions/pspell-config-create.xml
reference/pspell/functions/pspell-config-data-dir.xml
reference/pspell/functions/pspell-config-dict-dir.xml
reference/pspell/functions/pspell-config-ignore.xml
reference/pspell/functions/pspell-config-mode.xml
reference/pspell/functions/pspell-config-personal.xml
reference/pspell/functions/pspell-config-repl.xml
reference/pspell/functions/pspell-config-runtogether.xml
reference/pspell/functions/pspell-config-save-repl.xml
reference/pspell/functions/pspell-new-config.xml
reference/pspell/functions/pspell-new-personal.xml
reference/pspell/functions/pspell-new.xml
reference/pspell/functions/pspell-save-wordlist.xml
reference/pspell/functions/pspell-store-replacement.xml
reference/pspell/functions/pspell-suggest.xml
reference/pspell/pspell.config.xml
reference/pspell/pspell.dictionary.xml
reference/pspell/setup.xml

Use an Pspell\[Dictionary|Config] instance instead of a resource

Apply commit 81b23db050ac0627b056585c16bfe95445ae174e

---

reference/reflection/reflectiongenerator.xml

Fix typo in ReflectionGenerator introduction

---

language/predefined/closure.xml
language/predefined/generator.xml
language/predefined/weakreference.xml
reference/reflection/reflection.xml
reference/reflection/reflectionclass.xml
reference/reflection/reflectionclassconstant.xml
reference/reflection/reflectionclassconstant/isprivate.xml
reference/reflection/reflectionclassconstant/isprotected.xml
reference/reflection/reflectionclassconstant/ispublic.xml
reference/reflection/reflectionexception.xml
reference/reflection/reflectionextension.xml
reference/reflection/reflectiongenerator.xml
reference/reflection/reflectionparameter.xml
reference/reflection/reflectionproperty.xml
reference/reflection/reflectionproperty/isprivate.xml
reference/reflection/reflectionproperty/isprotected.xml
reference/reflection/reflectionproperty/ispublic.xml
reference/reflection/reflectionproperty/isstatic.xml
reference/reflection/reflectionzendextension.xml
reference/spl/functions/spl-autoload.xml
reference/url/functions/http-build-query.xml

Update to English

---

reference/array/functions/list.xml

Replaced "sont traités" by "à traiter"

Corrected french translation in list.xml

---

reference/strings/functions/setlocale.xml

#113 Strings.setlocale: Fix grammatical typo

---

reference/gnupg/functions/gnupg-adddecryptkey.xml
reference/gnupg/functions/gnupg-addencryptkey.xml
reference/gnupg/functions/gnupg-addsignkey.xml
reference/gnupg/functions/gnupg-cleardecryptkeys.xml
reference/gnupg/functions/gnupg-clearencryptkeys.xml
reference/gnupg/functions/gnupg-clearsignkeys.xml
reference/gnupg/functions/gnupg-decrypt.xml
reference/gnupg/functions/gnupg-decryptverify.xml
reference/gnupg/functions/gnupg-encrypt.xml
reference/gnupg/functions/gnupg-encryptsign.xml
reference/gnupg/functions/gnupg-export.xml
reference/gnupg/functions/gnupg-geterror.xml
reference/gnupg/functions/gnupg-getprotocol.xml
reference/gnupg/functions/gnupg-import.xml
reference/gnupg/functions/gnupg-keyinfo.xml
reference/gnupg/functions/gnupg-setarmor.xml
reference/gnupg/functions/gnupg-seterrormode.xml
reference/gnupg/functions/gnupg-setsignmode.xml
reference/gnupg/functions/gnupg-verify.xml

Apply php/doc-en@dc54babb688f72ee5b40cd6240a8d506623f5e10

Update to English GnuPG section

---

README.md
language/functions.xml
language/oop5/properties.xml
language/types/callable.xml

Hello,
This is just a tiny pull request to fix some typos.
Have a nice day.

Fix a bunch of typos

---

reference/mongodb/bson/binary/unserialize.xml
reference/mongodb/bson/dbpointer/unserialize.xml
reference/mongodb/bson/decimal128/unserialize.xml
reference/mongodb/bson/int64/unserialize.xml
reference/mongodb/bson/javascript/unserialize.xml
reference/mongodb/bson/maxkey/unserialize.xml
reference/mongodb/bson/minkey/unserialize.xml
reference/mongodb/bson/objectid/unserialize.xml
reference/mongodb/bson/regex/unserialize.xml
reference/mongodb/bson/symbol/unserialize.xml
reference/mongodb/bson/timestamp/unserialize.xml
reference/mongodb/bson/undefined/unserialize.xml
reference/mongodb/bson/utcdatetime/unserialize.xml

Apply php/doc-en@e4d26f1b4439401fc8726ecc13a8aea9cf861ca8

Apply php/doc-en@e4d26f1

---

language/oop5/decon.xml

Fautes d'orthographe, d'accords

Correction d'orthographe

---

reference/igbinary/book.xml
reference/igbinary/functions/igbinary-serialize.xml
reference/igbinary/functions/igbinary-unserialize.xml
reference/igbinary/ini.xml

Hi,
I wish to bring a small contribution to the php documentation if it is possible.
I hope this translation is not too bad.

Translate in French igbinary/book.xml

---

reference/spl/appenditerator/construct.xml
reference/spl/arrayiterator/construct.xml
reference/spl/arrayobject/construct.xml
reference/spl/callbackfilteriterator/construct.xml
reference/spl/filteriterator/construct.xml
reference/spl/infiniteiterator/construct.xml
reference/spl/iteratoriterator/construct.xml
reference/spl/multipleiterator/construct.xml
reference/spl/norewinditerator/construct.xml
reference/spl/parentiterator/construct.xml
reference/spl/recursivecachingiterator/construct.xml
reference/spl/recursivecallbackfilteriterator/construct.xml
reference/spl/recursivefilteriterator/construct.xml
reference/spl/recursiveiteratoriterator/construct.xml
reference/spl/recursivetreeiterator/construct.xml
reference/spl/splfileobject/construct.xml
reference/spl/splheap/construct.xml
reference/spl/splpriorityqueue/construct.xml
reference/spl/splqueue/construct.xml
reference/spl/splstack/construct.xml
reference/spl/spltempfileobject/construct.xml

Apply php/doc-en@fda6c4e

---

appendices/tokens.xml

Hi @Girgias,
As promised, here is my first modest contribution.
I'll have a look at the files you maintain in order to make a big update.
Cheers!

Update appendices/tokens.xms with current English version

---

reference/info/functions/cli-set-process-title.xml

See: https://www.php.net/manual/fr/function.cli-set-process-title.php#refsect1-function.cli-set-process-title-examples

[FR] Typo fix on cli-set-process-title

---

reference/array/functions/array-keys.xml

add missing method declaration

Sync with English

---

language/oop5/interfaces.xml

"Incohérences" plutôt que "inconsistances"

---

language/oop5/magic.xml

le sujet est "des méthodes spéciales" donc pluriel

conjugaison

---

reference/image/functions/imageavif.xml
reference/image/functions/imagecreatefromavif.xml

Bonjour,
Je souhaiterais apporter ma première contribution en traduisant la documentation des fonctions imageavif et imagecreatefromavif.

Translate the imageavif and imagecreatefromavif functions

---

language/oop5.xml

very minor change, related to grammar.

little grammar error in introduction

---

language/basic-syntax.xml

correcting a grammar error inFR

Update basic-syntax.xml / correcting a grammar error FR

---

reference/zip/ziparchive/close.xml

From https://github.com/php/doc-en/commit/d6ac0dd312ea431e902ef2b02f13a7dffa9ff75b

ZipArchive::close deletes file if empty

---

reference/filesystem/functions/fdatasync.xml
reference/filesystem/functions/fsync.xml
reference/filesystem/functions/stat.xml

Hello, some work on filesystem functions:
* Add missing translation in stat.xml
* Add and translate fdatasync.xml
* Add and translate fsync.xml

Add fsync & fdatasync + review stat

---

language-snippets.ent
reference/pgsql/functions/pg-fetch-array.xml

Slight correction of the commit bc46b170579b564ebd3143cfefba3c7e7a1bf179 =)

Slight correction

---

language-snippets.ent
reference/mongodb/bson/decimal128/construct.xml
reference/mongodb/bson/javascript/construct.xml
reference/mongodb/bson/objectid/construct.xml
reference/mongodb/bson/serializable.xml
reference/mongodb/bson/serializable/bsonserialize.xml
reference/mongodb/bson/unserializable.xml
reference/mongodb/bson/unserializable/bsonunserialize.xml
reference/mongodb/bson/utcdatetime/construct.xml
reference/mongodb/mongodb/driver/command/construct.xml
reference/mongodb/mongodb/driver/readpreference/construct.xml
reference/mongodb/mongodb/driver/server/executebulkwrite.xml
reference/mongodb/mongodb/driver/server/executecommand.xml
reference/mongodb/mongodb/driver/server/executequery.xml
reference/mongodb/mongodb/driver/writeconcern/construct.xml

Apply php/doc-en@734bafeaf071b78b15d375f9af583befddd8c2a2

Sync MongoDB section

---

reference/session/security.xml

Update security.xml for French translation

---

reference/zip/ziparchive/clearerror.xml
reference/zip/ziparchive/getstreamindex.xml
reference/zip/ziparchive/getstreamname.xml

Hi all, I added three files about Ziparchive who aren't translated actually.
Thank you for your review !

Add ziparchive missing files

---

reference/datetime/datetime/createfrominterface.xml
reference/datetime/datetimeimmutable/createfrominterface.xml

Hey guys, i added create From Interface method to DateTime and DateTimeImmutable.
Thanks for your proofreading !

Add createFromInterface to DateTime & DateTimeImmutable

---

reference/datetime/book.xml
reference/datetime/dateinterval.xml
reference/datetime/dateinterval/createfromdatestring.xml
reference/datetime/dateperiod/construct.xml
reference/datetime/datetime.xml
reference/datetime/datetime/createfromformat.xml
reference/datetime/datetimeimmutable/createfromformat.xml
reference/datetime/datetimeinterface.xml
reference/datetime/datetimeinterface/diff.xml
reference/datetime/datetimezone/getname.xml
reference/datetime/datetimezone/listidentifiers.xml
reference/datetime/formats.xml
reference/datetime/functions/date-create.xml
reference/datetime/functions/date-parse-from-format.xml
reference/datetime/functions/date-parse.xml
reference/datetime/functions/date-sun-info.xml
reference/datetime/functions/date-sunrise.xml
reference/datetime/functions/date-sunset.xml
reference/datetime/functions/date.xml
reference/datetime/functions/gmstrftime.xml
reference/datetime/functions/microtime.xml
reference/datetime/functions/mktime.xml
reference/datetime/functions/strftime.xml
reference/datetime/functions/strtotime.xml
reference/datetime/functions/timezone-version-get.xml
reference/datetime/ini.xml

Sync all the file of `reference/datetime`
Done:
If i forgot files tell me please

Sync DateTime section

---

reference/datetime/book.xml
reference/datetime/functions/date-create.xml

Hi again, I'm really sorry but after a little check on the revcheck tool I just see that I made some mistakes on the revision number... Sorry about that, here is the fix. Thanks for your patience and your help.

Fix revision number

---

appendices/migration70/new-features.xml
appendices/migration70/new-functions.xml

Apply php/doc-en@2166824

---

language-snippets.ent
reference/datetime/datetime/add.xml
reference/datetime/datetime/setdate.xml
reference/datetime/datetime/setisodate.xml
reference/datetime/datetime/settime.xml
reference/datetime/datetime/settimestamp.xml
reference/datetime/datetime/sub.xml
reference/datetime/datetimeimmutable/add.xml
reference/datetime/datetimeimmutable/setdate.xml
reference/datetime/datetimeimmutable/setisodate.xml
reference/datetime/datetimeimmutable/settime.xml
reference/datetime/datetimeimmutable/settimestamp.xml
reference/datetime/datetimeimmutable/sub.xml

Difficulties with `language-snippets.ent`.
Here's a diff to make it easier to review :)
http://doc.php.net/revcheck.php?p=plain&lang=fr&hbp=a3573c18b89fd32aca1c3924d3fd9568900b4a33&f=language-snippets.ent&c=on

Apply php/doc-en@769fdeb

---

appendices/migration73/other-changes.xml
appendices/migration74/incompatible.xml
chapters/intro.xml
faq/installation.xml
language/types/string.xml
reference/ctype/book.xml
reference/mbstring/functions/mb-ereg-replace.xml
reference/mbstring/functions/mb-ereg-search-init.xml
reference/mbstring/functions/mb-regex-encoding.xml
reference/mbstring/overloading.xml
reference/mbstring/supported-encodings.xml
reference/pcre/book.xml
reference/pcre/functions/preg-quote.xml
reference/pcre/pattern.differences.xml
reference/pcre/pattern.modifiers.xml
reference/pcre/pattern.syntax.xml
reference/strings/book.xml
reference/strings/functions/str-replace.xml
reference/strings/reference.xml

pcre change from rationnelles wording to régulières.

---

language/oop5/basic.xml
reference/calendar/functions/jdtofrench.xml
reference/calendar/functions/jdtojewish.xml
reference/datetime/datetime.xml
reference/datetime/datetimeimmutable.xml
reference/datetime/datetimeimmutable/settime.xml
reference/dom/domnode.xml
reference/funchand/functions/register-shutdown-function.xml
reference/hash/functions/hash-equals.xml
reference/image/functions/imagecolorset.xml
reference/intl/idn/idn-to-utf8.xml
reference/intl/intlbreakiterator/geterrormessage.xml
reference/intl/intlbreakiterator/getlocale.xml
reference/libxml/functions/libxml-set-external-entity-loader.xml
reference/session/sessionhandler.xml
reference/spl/splfileobject/getchildren.xml
reference/strings/functions/setlocale.xml
reference/strings/functions/stripos.xml
reference/strings/functions/stristr.xml
reference/strings/functions/strripos.xml

Sync various sections

---

.github/workflows/integrate.yaml
language/oop5/properties.xml
language/types.xml
language/types/declarations.xml
language/types/type-juggling.xml

Update french file to fix the build error.

Fix the build PHP documentation in FR language

---

reference/ldap/examples.xml

[Issues/317] fix typo

---

reference/datetime/constants.xml
reference/datetime/dateinterval.xml
reference/datetime/dateinterval/construct.xml
reference/datetime/dateinterval/createfromdatestring.xml
reference/datetime/dateinterval/format.xml
reference/datetime/dateperiod/construct.xml
reference/datetime/dateperiod/getdateinterval.xml
reference/datetime/dateperiod/getenddate.xml
reference/datetime/dateperiod/getstartdate.xml
reference/datetime/datetime.xml
reference/datetime/datetime/construct.xml
reference/datetime/datetime/createfromformat.xml
reference/datetime/datetime/createfrominterface.xml
reference/datetime/datetimeimmutable.xml
reference/datetime/datetimeimmutable/createfromformat.xml
reference/datetime/datetimeimmutable/createfrominterface.xml
reference/datetime/datetimeinterface.xml
reference/datetime/datetimeinterface/diff.xml
reference/datetime/datetimeinterface/format.xml
reference/datetime/datetimezone/getname.xml
reference/datetime/datetimezone/listidentifiers.xml
reference/datetime/functions/date-create.xml
reference/datetime/functions/date.xml

Hi everyone,
Some work on the date section
Thanks for your review
cheers

Sync various Date related files

---

language-snippets.ent

mysql.query typo fix

---

reference/array/functions/range.xml

Corrected typo in the word "utilisé"

Typo in range.xml

---

reference/url/functions/http-build-query.xml
reference/var/functions/unserialize.xml
reference/var/functions/var-export.xml
reference/xml/functions/xml-get-current-byte-index.xml
reference/xml/functions/xml-get-current-column-number.xml
reference/xml/functions/xml-get-current-line-number.xml
reference/xml/functions/xml-get-error-code.xml
reference/zlib/functions/gzpassthru.xml

Hello, 
i synced some sections
Thanks for the proofreading :)

Sync various section

---

reference/strings/functions/implode.xml

Removed extra "e" in "nommées".

Corrected typo in implode.xml

---

reference/pdo/connections.xml

Correcting typos in persistent connections paragraph.
Verified with bonpatron corrector.

French typos

---

reference/datetime/functions/date-create-immutable.xml
reference/datetime/functions/date-get-last-errors.xml
reference/datetime/functions/date-parse.xml
reference/mysqli/mysqli/multi-query.xml
reference/mysqli/mysqli/query.xml
reference/mysqli/mysqli/real-query.xml
reference/mysqli/mysqli/store-result.xml
reference/mysqli/mysqli_result/fetch-field-direct.xml
reference/mysqli/mysqli_result/fetch-field.xml
reference/mysqli/quickstart.xml

Hi,
Synced:
* datetime/functions
* mysqli
Thanks for proofreading

Sync few sections

---

reference/simplexml/simplexmliterator.xml

Sync SimpleXMLIterator

---

reference/xml/functions/xml-set-character-data-handler.xml
reference/xml/functions/xml-set-default-handler.xml
reference/xml/functions/xml-set-element-handler.xml
reference/xml/functions/xml-set-end-namespace-decl-handler.xml
reference/xml/functions/xml-set-external-entity-ref-handler.xml
reference/xml/functions/xml-set-notation-decl-handler.xml
reference/xml/functions/xml-set-object.xml
reference/xml/functions/xml-set-processing-instruction-handler.xml
reference/xml/functions/xml-set-start-namespace-decl-handler.xml
reference/xml/functions/xml-set-unparsed-entity-decl-handler.xml

Thanks for proofreading as always !

sync reference/xml

---

language/functions.xml

> naturel yaourt
sounded weird in French / ne sonnait pas français.

functions.xml: fix wrong French sentence

---

appendices/migration80/deprecated.xml
appendices/migration80/incompatible.xml

@Girgias Have fun c'est des gros fichiers. J'avoue que à la fin j'était pas mal moins attentif. Donc hésite pas à faire des retouches et à repousser des modifications directement dans la PR. Ca nous fera gagner du temps :)

Sync appendices/migration80/{deprecated.xml,incompatible.xml}

---

reference/datetime/datetimeinterface/format.xml
reference/datetime/datetimeinterface/getoffset.xml
reference/datetime/datetimeinterface/gettimestamp.xml
reference/datetime/datetimeinterface/gettimezone.xml
reference/datetime/datetimeinterface/wakeup.xml
reference/datetime/functions/gmmktime.xml
reference/datetime/functions/mktime.xml

Hello there, little work on datetime section !
(i messed up the last branch sorry)
Thanks for proofreading :)

sync: reference/datetime

---

reference/zip/constants.xml
reference/zip/ziparchive/close.xml

Apply php/doc-en@a70ce62

---

language/predefined/arrayaccess.xml
language/predefined/backedenum.xml
language/predefined/iterator.xml
language/predefined/iteratoraggregate.xml
language/predefined/serializable.xml
language/predefined/stringable.xml
language/predefined/throwable.xml
language/predefined/traversable.xml
language/predefined/unitenum.xml
reference/random/random.cryptosafeengine.xml
reference/random/random.engine.xml
reference/reflection/reflector.xml
reference/session/sessionhandlerinterface.xml
reference/session/sessionidinterface.xml
reference/session/sessionupdatetimestamphandlerinterface.xml
reference/spl/countable.xml
reference/spl/outeriterator.xml
reference/spl/recursiveiterator.xml
reference/spl/seekableiterator.xml
reference/spl/splobserver.xml
reference/spl/splsubject.xml

Apply php/doc-en@96a8379

---

extensions.ent
features/dtrace.xml
language-snippets.ent
language/wrappers/audio.xml
language/wrappers/compression.xml
language/wrappers/data.xml
language/wrappers/expect.xml
language/wrappers/file.xml
language/wrappers/ftp.xml
language/wrappers/glob.xml
language/wrappers/http.xml
language/wrappers/phar.xml
language/wrappers/php.xml
language/wrappers/rar.xml
language/wrappers/ssh2.xml

Drive by fixes for wrappers
Vu que je sais pas conjuguer.

Partial-sync docs with EN after PECL change

---

reference/mysqli/mysqli_result/fetch-field.xml
reference/mysqli/mysqli_result/field-seek.xml

@Girgias Je pense que le dernier commit sur `fetch-field.xml` était une erreur j'ai donc revert le fichier.

Sync reference/mysqli/mysqli_result

---

reference/ffi/ctype/getalignment.xml
reference/ffi/ctype/getarrayelementtype.xml
reference/ffi/ctype/getarraylength.xml
reference/ffi/ctype/getattributes.xml
reference/ffi/ctype/getenumkind.xml
reference/ffi/ctype/getfuncabi.xml
reference/ffi/ctype/getfuncparametercount.xml
reference/ffi/ctype/getfuncparametertype.xml
reference/ffi/ctype/getfuncreturntype.xml
reference/ffi/ctype/getkind.xml
reference/ffi/ctype/getname.xml
reference/ffi/ctype/getpointertype.xml
reference/ffi/ctype/getsize.xml
reference/ffi/ctype/getstructfieldnames.xml
reference/ffi/ctype/getstructfieldoffset.xml
reference/ffi/ctype/getstructfieldtype.xml

@Girgias There is no text to translate there but I created the files just so they can be tracked in http://doc.php.net/revcheck.php?p=filesummary&lang=fr

Translate reference/ffi/ctype

---

reference/mbstring/functions/mb-str-split.xml
reference/sockets/addressinfo.xml
reference/sockets/socket.xml

Hi, just added some untranslated files:
*  reference/mbstring/functions/mb-str-split.xml
*  reference/sockets/addressinfo.xml
*  reference/sockets/socket.xml
Thanks for proofreading !

Add missing translation

---

reference/dom/domdocument/loadhtml.xml
reference/dom/domdocument/loadhtmlfile.xml
reference/dom/domdocument/xinclude.xml
reference/simplexml/functions/simplexml-load-file.xml
reference/simplexml/functions/simplexml-load-string.xml

Hello, following the addition of #617, use `&dom.parameter.options;` snippet like the EN doc (php/doc-en@d2939d4)

use dom.parameter.options

---

language-snippets.ent

Hi 
sorry I forgot it yesterday so I just updated the revision

fix: forgotten revision

---

reference/strings/functions/str-decrement.xml
reference/strings/functions/str-increment.xml

There is the translations of `str_increment` ans `str_decrement` functions of php8.3

Add `str_increment` and `str_decrement` functions

---

install/unix/apache2.xml

Fixed typo in apache2.xml

---

reference/strings/functions/str-contains.xml
reference/strings/functions/str-ends-with.xml
reference/strings/functions/str-starts-with.xml

Hello !
Added missing translations for `strings/functions`

Add missing translations in strings/functions

---

reference/gmp/gmp/construct.xml

Hi, just fixed a missed one
Thanks !

Fix missing translation

---

reference/gmp/functions/gmp-divexact.xml
reference/gmp/gmp.xml

Me again...
I looked the revcheck tool just after my last PR sorry :/ 
`reference/gmp/functions/gmp-divexact.xml` has no change because it was just a typo in EN
Sorry for these 2 PR on the same topic

sync: gmp section

---

language/basic-syntax.xml

Update basic-syntax.xml - small typos

---

reference/dom/domnode/getlineno.xml

Hello,
just synced `reference/dom/domnode/getlineno.xml`
Have a nice day and merry Christmas !

sync reference/dom/domnode/getlineno.xml

---

reference/pdo/pdostatement/setfetchmode.xml

Sync pdo setfetchmode

---

language/predefined/attributes/override.xml
language/predefined/attributes/override/construct.xml

Hello, added files to Override attribute.
I assume `language/predefined/attributes/override.xml` is not fully completed in English one. If I have some times next week I will make a proposal in EN doc, or complete the FR if someone does it before me.
Have a nice day !

Add Override translations

---

reference/oci8/setup.xml

Hi,
Here is a fix for the OCI8 requirements typo.

typo fix in OCI8 setup page (#829)

---

reference/pdo/pdorow.xml

Here is the translation of `PDORow`﻿ class :)

Translate `PDORow`class

---

reference/reflection/reflectionattribute/construct.xml
reference/reflection/reflectionattribute/getarguments.xml
reference/reflection/reflectionattribute/getname.xml
reference/reflection/reflectionattribute/gettarget.xml
reference/reflection/reflectionattribute/isrepeated.xml
reference/reflection/reflectionattribute/newinstance.xml

There is the translation of `ReflectionAttribute`﻿ functions

Translate `ReflectionAttribute`  function

---

reference/reflection/reflectionmethod/createfrommethodname.xml
reference/reflection/reflectionmethod/hasprototype.xml

Here is the missing translation of `ReflectionMethod` functions

Translate missing reflectionmethod functions

---

reference/yaml/functions/yaml-parse-file.xml

Hi, the parameter was already well named in French doc's...

sync YAML section

---

install/unix/index.xml

Hi !
Thanks for your proofreading as always

Sync install Section

---

reference/reflection/reflectionproperty/getattributes.xml
reference/reflection/reflectionproperty/getdefaultvalue.xml
reference/reflection/reflectionproperty/hasdefaultvalue.xml
reference/reflection/reflectionproperty/ispromoted.xml
reference/reflection/reflectionproperty/isreadonly.xml

Translate following functions: 
- `ReflectionProperty::getAttributes()`
- `ReflectionProperty::getDefaultValue()`
- `ReflectionProperty::hasDefaultValue()`
- `ReflectionProperty::isPromoted()`
- `ReflectionProperty::isReadOnly()`

Translate `ReflectionProperty` functions

---

reference/datetime/functions/gmdate.xml
reference/datetime/functions/gmstrftime.xml

datetime CUT -> TUC (Temps Universel Coordonne).

---

reference/reflection/reflectionenum/construct.xml
reference/reflection/reflectionenum/getbackingtype.xml
reference/reflection/reflectionenum/getcase.xml
reference/reflection/reflectionenum/getcases.xml
reference/reflection/reflectionenum/hascase.xml
reference/reflection/reflectionenum/isbacked.xml

Here is the translation of the `ReflectionEnum` class
- `ReflectionEnum::__construct()`
- `ReflectionEnum::getCase()`
- `ReflectionEnum::getCases()`
- `ReflectionEnum::getBackingType()`
- `ReflectionEnum::hasCase()`
- `ReflectionEnum::isBacked()`

Translate `ReflectionEnum` class

---

reference/strings/functions/strtok.xml

Fix spelling on strtok

---

reference/reflection/reflectionenum/hascase.xml

http://doc.php.net/revcheck.php?p=misstags&lang=fr
Oops 😅

Fix typo in revision commit

---

appendices/history.xml

Sync: history with EN

---

TRADUCTIONS.txt
language/enumerations.xml
language/predefined/backedenum.xml
reference/reflection/reflectionenumbackedcase.xml

Following [this dicussion](https://github.com/php/doc-fr/pull/1049#discussion_r1689200183)
I hope I haven't forgotten anything 😅

Replace `énumération soutenue` with `énumération avec valeur de base`

---

reference/apcu/functions/apcu-exists.xml

Sync apcu with EN

---

reference/array/functions/array-filter.xml

Sync array-filter with EN

---

reference/datetime/constants.xml
reference/datetime/setup.xml

See php/doc-en#3559
Partially php/doc-en#3545

Sync datetime with EN

---

reference/outcontrol/constants.xml
reference/outcontrol/setup.xml

See php/doc-en#3587
Partially php/doc-en#3545

Sync outcontrol with EN

---

reference/reflection/reflectionenumbackedcase/construct.xml
reference/reflection/reflectionenumbackedcase/getbackingvalue.xml

Hello, 
Here is the translation of missing `ReflectionEnumBackedCase` methods
- `ReflectionEnumBackedCase::__construct()`
- `ReflectionEnumBackedCase::getBackingValue()`

Translate `ReflectionEnumBackedCase` methods

---

reference/hash/functions/hash-file.xml
reference/hash/functions/hash-hkdf.xml
reference/hash/functions/hash-hmac-file.xml
reference/hash/functions/hash-hmac.xml
reference/hash/functions/hash-init.xml
reference/hash/functions/hash-pbkdf2.xml
reference/hash/functions/hash.xml

Sync hash functions with en

---

reference/reflection/reflectionenumunitcase/construct.xml
reference/reflection/reflectionenumunitcase/getenum.xml
reference/reflection/reflectionenumunitcase/getvalue.xml

Here is the translation of `ReflectionEnumUnitCase` methods:
-  `ReflectionEnumUnitCase::__construct()`
-  `ReflectionEnumUnitCase::getEnum()`
- `ReflectionEnumUnitCase::getValue()`

Translate `ReflectionEnumUnitCase` methods

---

reference/reflection/reflectionintersectiontype/gettypes.xml

Here is the translation of missing `ReflectionIntersectionType` method
- `ReflectionIntersectionType::getTypes()`

Translate `ReflectionIntersectionType` 

---

appendices/migration80/new-features.xml
appendices/migration80/other-changes.xml

Kind of a big file here. 
Not sure about all the translations.

Translate `migration80`

---

reference/mongodb/bson/utcdatetime/todatetimeimmutable.xml

Sorry for the PR spam but I was very motivated 😅

Translate `MongoDB\BSON\utcdatetime\toDateTimeImmutable()`

---

reference/com/com-safearray-proxy.xml
reference/intl/intlcalendar/setdate.xml
reference/intl/intlcalendar/setdatetime.xml

Oops ^^'
[Source](http://doc.php.net/revcheck.php?p=misstags&lang=fr)

Add en-revision

---

reference/cmark/commonmark/cql/construct.xml
reference/cmark/commonmark/cql/invoke.xml
reference/cmark/commonmark/interfaces/ivisitable/accept.xml
reference/cmark/commonmark/interfaces/ivisitor/enter.xml
reference/cmark/commonmark/interfaces/ivisitor/leave.xml
reference/cmark/commonmark/parser/construct.xml
reference/cmark/commonmark/parser/finish.xml
reference/cmark/commonmark/parser/parse.xml

Translation of 
- `CommonMark\CQL::_construct()`
- `CommonMark\CQL::_invoke()`
- `CommonMark\Interfaces\Ivistable::accept()`
- `CommonMark\Interfaces\IVisitor::enter()`
- `CommonMark\Interfaces\IVisitor::leave()`
- `CommonMark\Parser::__construct()`
- `CommonMark\Parser::finish()`
- `CommonMark\Parser::parse()`

Commonmark

---

reference/cmark/commonmark/node/accept.xml
reference/cmark/commonmark/node/appendchild.xml
reference/cmark/commonmark/node/bulletlist/construct.xml
reference/cmark/commonmark/node/codeblock/construct.xml
reference/cmark/commonmark/node/heading/construct.xml
reference/cmark/commonmark/node/image/construct.xml
reference/cmark/commonmark/node/insertafter.xml
reference/cmark/commonmark/node/insertbefore.xml
reference/cmark/commonmark/node/link/construct.xml
reference/cmark/commonmark/node/orderedlist/construct.xml
reference/cmark/commonmark/node/prependchild.xml
reference/cmark/commonmark/node/replace.xml
reference/cmark/commonmark/node/text/construct.xml
reference/cmark/commonmark/node/unlink.xml

Translation of commonmark/node/*

Translate `Commonmark\Node`

---

reference/curl/constants_curl_error.xml
reference/curl/constants_curl_getinfo.xml
reference/curl/constants_curl_multi.xml
reference/curl/constants_curl_multi_setopt.xml
reference/curl/constants_curl_pause.xml
reference/curl/constants_curl_share_setopt.xml
reference/curl/constants_curlproto.xml

Here are almost all curl constants
I will translate `setopt` in another PR

Curl function

---

reference/dom/domcharacterdata/after.xml
reference/dom/domcharacterdata/before.xml
reference/dom/domcharacterdata/remove.xml
reference/dom/domcharacterdata/replacewith.xml
reference/dom/domnamespacenode.xml

Translate `DOMNameSpaceNode`
and 
- `Dom\DOMCharacterData::after()`
- `Dom\DOMCharacterData::before()`
- `Dom\DOMCharacterData::remove()`
- `Dom\DOMCharacterData::replaceWith()`

Translate Dom 

---

reference/curl/constants_curl_setopt.xml

This is big file here.
I hope I haven't missed anything ^^'

Translate curl_setopt constants

---

reference/intl/normalizer/get-raw-decomposition.xml
reference/intl/spoofchecker/setrestrictionlevel.xml

Translate :
- `Normalizer::getRawDecomposition()`
- `Spoofchecker::setRestrictionLevel()`

Translate missing intl methods

---

reference/intl/intlgregoriancalendar/createfromdate.xml
reference/intl/intlgregoriancalendar/createfromdatetime.xml

Source: [doc.php.net](http://doc.php.net/revcheck.php?p=misstags&lang=fr)

Add missing en-revision to intlgregoriancalendar

---

reference/ui/ui/controls/box/ispadded.xml

Keep padding for translation

---

appendices/migration83/new-functions.xml

See [doc.php.net](http://doc.php.net/revcheck.php?p=misstags&lang=fr)

Fix Typo in commit hash

---

faq/com.xml

Revert "FAQ sync with EN"

---

reference/pcre/functions/preg-match-all.xml

Fix GH-1561

---

features/commandline.xml
install/windows/manual.xml
language/operators/increment.xml
language/operators/string.xml
reference/igbinary/functions/igbinary-serialize.xml
reference/mysqli/summary.xml
reference/oci8/testing.xml
reference/var/functions/is-callable.xml
reference/zip/ziparchive/unchangearchive.xml

These are mistakes in the French documentation due to badly syncing with doc-en

Fix some RelaxNG violations

---

reference/tidy/constants.xml

Revert "TIDY sync with EN"

---

reference/reflection/reflectionproperty/islazy.xml
reference/reflection/reflectionproperty/setrawvaluewithoutlazyinitialization.xml
reference/reflection/reflectionproperty/skiplazyinitialization.xml

Here is the translation of missing `ReflectionProperty` methods
- `ReflectionProperty::isLazy()`
- `ReflectionProperty::setRawValueWithoutLazyInitialization()`
- `ReflectionProperty::skipLazyInitialization()`

Translate new `ReflectionProperty` methods

---

language/oop5/lazy-objects.xml
reference/reflection/reflectionclass/getlazyinitializer.xml
reference/reflection/reflectionclass/marklazyobjectasinitialized.xml
reference/reflection/reflectionclass/newlazyproxy.xml

See https://github.com/php/doc-fr/pull/1694#discussion_r1831647390

Change `usine` to `fabrique`

---

reference/intl/grapheme/grapheme-str-split.xml

See https://github.com/php/doc-fr/pull/1667/files#r1833836888

Translate missing return value for `grapheme_str_split`

---

reference/spl/splfileobject/setcsvcontrol.xml

Sync with EN
Fix various typos 
Should I change to `` ?

Sync `setcsvcontrol` with EN

---

reference/apcu/apcuiterator.xml

This pull request includes changes to the `reference/apcu/apcuiterator.xml` file to improve the documentation by correcting translating the title to French.
Documentation improvements:
* Translated the title of the `APCUIterator` class to French.

fix wording translate page APCUIterator

---

reference/shmop/functions/shmop-read.xml

This pull request includes minor updates to the `reference/shmop/functions/shmop-read.xml` file to update the revision identifier and correct a translation in the return values section.
* Updated the revision identifier in the XML header comment.
* Corrected the French translation in the return values section by removing an incorrect phrase.

update function shmop read doc en

---

README.md

fix grammar readme :)

---

.github/ISSUE_TEMPLATE/translation-issue.md

I don't know if it's a good idea, but integrating a template for issues might be a good idea, don't you think ?

add issue templates translation

---

reference/ui/ui.controls.button.xml
reference/ui/ui.draw.text.font.descriptor.xml
reference/ui/ui/controls/multilineentry/append.xml

This pull request includes several corrections to French translations in the XML documentation files. The most important changes include fixing typographical errors and translating English text to French.
Translation corrections:
* [`reference/ui/ui.controls.button.xml`](diffhunk://#diff-0e0955f5f654846937ac5a87be6915d721b48d4f221500a353f7aa6420048828L5-R5): Corrected the French translation of "Button de Contrôle" to "Bouton de Contrôle".
* [`reference/ui/ui.draw.text.font.descriptor.xml`](diffhunk://#diff-056835e0c2ecef116cc2a83741e30383480bbbb28090f4197bb0841a52e1eed7L14-R14): Corrected the French translation of "Descrit une police" to "Décrit une police".
* [`reference/ui/ui/controls/multilineentry/append.xml`](diffhunk://#diff-dd9f84f67d656d30ba4618cecd3f58ca099214452df35ee9b55af5063c8 …

fix many problem ui
